version: 2
jobs:
  deployprod:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/firebase-vuejs-fe
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: Install Firebase Globally
          command: sudo npm install -g firebase-tools
      - run:
          name: Init Environment Variables
          command: echo VUE_APP_GOOGLE_API_KEY=$VUE_APP_GOOGLE_API_KEY >> env &&
            echo VUE_APP_FIREBASE_API_KEY=$VUE_APP_FIREBASE_API_KEY >> env &&
            echo VUE_APP_FIREBASE_AUTH_DOMAIN=$VUE_APP_FIREBASE_AUTH_DOMAIN >> env &&
            echo VUE_APP_FIREBASE_DATABASE_URL=$VUE_APP_FIREBASE_DATABASE_URL >> env &&
            echo VUE_APP_FIREBASE_PROJECT_ID=$VUE_APP_FIREBASE_PROJECT_ID >> env &&
            echo VUE_APP_FIREBASE_STORAGE_BUCKET=$VUE_APP_FIREBASE_STORAGE_BUCKET >> env &&
            echo VUE_APP_FIREBASE_MESSAGING_SENDER_ID=$VUE_APP_FIREBASE_MESSAGING_SENDER_ID >> env &&
            echo VUE_APP_FIREBASE_APP_ID=$VUE_APP_FIREBASE_APP_ID >> env
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Test
          command: npm run test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Firebase Deploy
          command: firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deployprod:
          context: eclipx-firebase-vuejs
          filters:
            branches:
              only:
                - master
